language: c
sudo: required
branches:
  only:
    - master
env:
  - OS=fedora-latest
  - OS=ubuntu-devel
  - OS=ubuntu-latest
  - OS=ubuntu-lts
services:
  - docker
before_install:
  - sudo apt-get update && sudo apt-get -y install docker-ce
  - docker pull "cangjians/libcangjie:${OS}"
  - docker build --build-arg OS=${OS} --tag "cangjians/pycangjie:${OS}" .
script:
  - docker run --rm "cangjians/pycangjie:${OS}" bash -c '. /usr/lib/os-release && echo $PRETTY_NAME'
  - docker run --rm "cangjians/pycangjie:${OS}" make distcheck
