language: c
sudo: required
branches:
  only:
    - master
services:
  - docker
env:
  - OS=fedora-latest
  - OS=ubuntu-devel
  - OS=ubuntu-latest
  - OS=ubuntu-lts
before_install:
  - |
      mkdir tmp
      sudo docker pull "cangjians/build-essential:${OS}"
      sudo docker tag "cangjians/build-essential:${OS}" "cangjians/build-essential:latest"
      echo
      echo OS=$(sudo docker run -it --rm "cangjians/build-essential:latest" -c "cat /var/version")
      echo ---------------
      git clone -b docker https://github.com/Cangjians/libcangjie.git tmp/libcangjie
      sudo docker build -t "cangjians/libcangjie" tmp/libcangjie/.
      sudo docker build -t "cangjians/pycangjie" .
script:
  - |
      sudo docker run -it --rm "cangjians/pycangjie" make check distcheck
